# Form implementation generated from reading ui file 'candidate_menu.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(463, 639)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(463, 639))
        Form.setMaximumSize(QtCore.QSize(463, 639))
        self.candidate_app_label = QtWidgets.QLabel(parent=Form)
        self.candidate_app_label.setGeometry(QtCore.QRect(100, 50, 270, 52))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.candidate_app_label.setFont(font)
        self.candidate_app_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.candidate_app_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.candidate_app_label.setObjectName("candidate_app_label")
        self.john_button = QtWidgets.QPushButton(parent=Form)
        self.john_button.setGeometry(QtCore.QRect(80, 350, 111, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.john_button.setFont(font)
        self.john_button.setObjectName("john_button")
        self.jane_button = QtWidgets.QPushButton(parent=Form)
        self.jane_button.setGeometry(QtCore.QRect(270, 350, 111, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.jane_button.setFont(font)
        self.jane_button.setObjectName("jane_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.candidate_app_label.setText(_translate("Form", "CANDIDATES"))
        self.john_button.setText(_translate("Form", "John"))
        self.jane_button.setText(_translate("Form", "Jane"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
