# Form implementation generated from reading ui file 'final_menu.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(463, 639)
        Form.setMinimumSize(QtCore.QSize(463, 639))
        Form.setMaximumSize(QtCore.QSize(463, 639))
        self.john_final = QtWidgets.QLabel(parent=Form)
        self.john_final.setGeometry(QtCore.QRect(50, 180, 371, 91))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.john_final.setFont(font)
        self.john_final.setObjectName("john_final")
        self.jane_final = QtWidgets.QLabel(parent=Form)
        self.jane_final.setGeometry(QtCore.QRect(50, 320, 371, 91))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.jane_final.setFont(font)
        self.jane_final.setObjectName("jane_final")
        self.total_final = QtWidgets.QLabel(parent=Form)
        self.total_final.setGeometry(QtCore.QRect(50, 460, 371, 91))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.total_final.setFont(font)
        self.total_final.setObjectName("total_final")
        self.final_label = QtWidgets.QLabel(parent=Form)
        self.final_label.setGeometry(QtCore.QRect(70, 50, 321, 52))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.final_label.setFont(font)
        self.final_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.final_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.final_label.setObjectName("final_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FinalWindow"))
        self.john_final.setText(_translate("Form", "TextLabel"))
        self.jane_final.setText(_translate("Form", "TextLabel"))
        self.total_final.setText(_translate("Form", "TextLabel"))
        self.final_label.setText(_translate("Form", "FINAL RESULTS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
